steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: [
      'build',
      '--no-cache',
      '-t',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '-f',
      'Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [
      'push',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      '$_SERVICE_NAME',
      '--platform',
      'managed',
      '--region',
      '$_DEPLOY_REGION',
      '--image',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '--set-env-vars',
      'AUTH_TOKEN=${_AUTH_TOKEN}',
      '--labels',
      'managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID',
      '--quiet',
      '--allow-unauthenticated'
    ]

images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
